site_name: QP Utils Documentation

theme:
  name: readthedocs

plugins:
- search
- mkdocstrings

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  - javascript/config.js

extra_css:
  - css/style.css

nav:
  - Home: index.md
  - QP: qp.md
  - OCP QP: ocp.md